# Generated by Django 5.0.2 on 2026-04-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0003_rename_materias_array_maestros_materias_json_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
    ]
