# Generated by Django 5.0.2 on 2026-05-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0005_administradores_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='grado_academico',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
